version: '2.1'
services:
  frontend:
    build:
      dockerfile: ./docker/frontend.Dockerfile
      context: .
    volumes:
      - static:/data/static/
      - ./frontend/src:/usr/local/app/src
  backend:
    build:
      dockerfile: ./docker/backend.Dockerfile
      context: .
    volumes:
      - static:/data/static/
      - ./backend:/go/src/automoderation
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped
volumes:
  static:
