version: '2.1'
services:
  frontend:
    extends:
      file: ./docker/services.yml
      service: frontend-${MODE:-dev}
  backend:
    extends:
      file: ./docker/services.yml
      service: backend-${MODE:-dev}
    ports:
      - "${PORT:-8080}:80"
volumes:
  static:
