apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "automoderation.fullname" . }}"
  annotations:
    {{ include .Values.ingress.annotations . | indent 4 }}
spec:
  tls:
  - hosts:
    - {{ .Values.host | quote }}
      secretName: "{{ template "automoderation.fullname" . }}-tls"
  rules:
  - host:  {{ .Values.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ template "automoderation.fullname" . }}"
          servicePort: http
