apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "automoderation.fullname" . }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.host | quote }}
    secretName: "{{ template "automoderation.fullname" . }}-tls"
  rules:
  - host:  {{ .Values.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ template "automoderation.fullname" . }}"
          servicePort: http
