apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "automoderation.fullname" . }}"
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
  - "{{ $key }}: {{ $value | quote }}"
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.host | quote }}
      secretName: "{{ template "automoderation.fullname" . }}-tls"
  rules:
  - host:  {{ .Values.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ template "automoderation.fullname" . }}"
          servicePort: http
