apiVersion: v1
kind: Service
metadata:
  name: "{{ template "automoderation.fullname" . }}"
  labels:
    {{ include "base_labels" . | indent 4 }}
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    {{ include "base_labels" . | indent 4 }}
