apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "automoderation.fullname" . }}-unicorn
  labels:
    {{ include "base_labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "base_labels" . | indent 6 }}
  template:
    metadata:
      name: {{ template "automoderation.fullname" . }}-backend
      labels:
        {{ include "base_labels" . | indent 8 }}
    spec:
      initContainers:
      - name: frontend
        image: "{{ .Values.image.repository }}-frontend:{{ .Values.image.tag }}"
        volumeMounts:
        - name: front-data
          mountPath: /usr/local/app/dist
        - mountPath: /etc/extra_html/
          name: extra-html
        env:
        - name: NODE_ENV
          value: production
        - name: EXTRA_HEAD
          value: /etc/extra_html/extra_head.html
        - name: EXTRA_BODY
          value: /etc/extra_html/extra_body.html
        {{- range $key, $value := .Values.frontend.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.frontend.secrets }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}-backend:{{ .Values.image.tag }}"
        env:
        - name: REDIS_URL
          value: "{{ .Release.Name }}-redis-master:6379"
        - name: REDIS_DB
          value: '0'
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password | quote }}
        - name: POSTGRES_URL
          value: {{ .Values.backend.postgres_url | quote }}
        {{- range $key, $value := .Values.backend.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.backend.secrets }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
          - name: http
            protocol: TCP
            containerPort: 80
        volumeMounts:
        - name: front-data
          mountPath: /data/static/
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
      volumes:
      - name: front-data
        emptyDir: {}
      - name: extra-html
        configMap:
          name: "{{ template "automoderation.fullname" . }}-extra-html"
          items:
          - key: extra_head.html
            path: extra_head.html
          - key: extra_body.html
            path: extra_body.html
