host: automoderation.y.friendzone.bot

image:
  repository: docker-registry.friendzone.bot/main/automoderation
  tag: latest

backend:
  env: []
  secrets: []
  postgres_url: ""

redis:
  password: ""

frontend:
  env: []
  secrets: []
  extra_head: ''
  extra_body: ''
