version: '2.1'
services:
  frontend:
    build:
      dockerfile: ./docker/frontend.Dockerfile
      context: ..
    volumes:
      - static:/usr/local/app/dist
    restart: unless-stopped
  frontend-prod:
    extends: frontend
    environment:
      NODE_ENV: production
  frontend-dev:
    environment:
      NODE_ENV: debug
    extends: frontend
    volumes:
      - ../frontend/src:/usr/local/app/src
      - ../frontend/webpack.config.js:/usr/local/app/webpack.config.js:ro
      - ../frontend/package.json:/usr/local/app/package.json:ro
      - ../.git:/usr/local/app/.git:ro
    command: ["npm", "run", "watch"]
  backend:
    build:
      dockerfile: ./docker/backend.Dockerfile
      context: ..
    volumes:
      - static:/data/static/
  backend-prod:
    extends: backend
    restart: unless-stopped
  backend-dev:
    extends: backend
    volumes:
      - ../backend:/go/src/automoderation
