export const SET_ROOM_NAME = 'SET_ROOM_NAME'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_TOKEN = 'SET_TOKEN'

export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED'

export const MESSAGE_ADDED = 'MESSAGE_ADDED'
export const MESSAGE_DELETED = 'MESSAGE_DELETED'
